#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = ' {{ .Path }}'
    background = ''
    foreground = '#0CA0D8'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = '#007ACC'
    template = " \uf017 {{ .CurrentDate | date .Format }} "

    [blocks.segments.properties]
      time_format = "15:04:05"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    background = ''
    foreground = '#44883e'
    template = "\ue718 {{ .Full }} "
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      fetch_package_manager = true

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    powerline_symbol = ''
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    background = ''
    foreground = '#14A5AE'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    template = ' '
    background = ''
    foreground = '#cd5e42'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '# '
    background = ''
    foreground = '#CD4277'
    Text = ''
    Duration = 0
    NameLength = 0
